apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplewebapp
  template:
    metadata:
      labels:
        app: simplewebapp
    spec:
      containers:
      - name: simplewebapp
        image: sangeetha1501/simplewebapp:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simplewebapp-service
spec:
  selector:
    app: simplewebapp
  ports:
    - protocol: TCP
      port: 80          # This is the port on which the service is exposed
      targetPort: 80     # This is the port your container is listening on
  type: NodePort       # Exposes the service on a static port on each node
